### PR TITLE
To handle cases where an insert statement is created with empty insert data

### PR DESCRIPTION
**Pull request by Hiteshm01**
Fix for insert statement with empty array without object i.e. []. currently it is issuing select * from table_name in this case.
For array with empty object, it will behave as default.

### CODE REVIEW

**Comment by brianc** [comment]
Nice! Thanks @Hiteshm01 

Would you be able to put together a test case for this?

**Comment by Hiteshm01** [comment]
@brianc  I found the root cause which was causing problem but could only manage a hackish handling in code. Could you please have a look at my latest commit?

**Comment by Hiteshm01** [comment]
@brianc , Were you able to verify it?

**Comment by brianc** [comment]
Sorry I missed this earlier! Your code looks good to me - there's a merge conflict currently. :( Once you get that resolved I'll happily pull it in! :+1:

**Comment by Hiteshm01** [comment]
@brianc , conflict resolved.

**Comment by brianc** [comment]
Awesome! Thanks! Merging & pushing new patch version now.

**Comment by spion** [comment]
This doesn't always work in pg; will produce a test case

**Comment by Hiteshm01** [comment]
@spion , I agree. It should not but as per what earlier implementation was returning a "select * from <table>" in this case which was disastrous  in any production table. My fix isn't ideal as it is only avoiding trouble.
Suggestions/improvements welcome.

**Comment by spion** [comment]
@Hiteshm01 a harmless query like `select (1 = 1)` would probably be ideal there.

**Comment by Hiteshm01** [comment]
@spion , That will be a better fix but do you think returning a select statement when requested for an insert statement is correct behavior?

**Comment by spion** [comment]
Well, not really - its just backward-compatible behavior. The `correct` backward-incompatible behavior would be to not generate a query.

**Comment by Hiteshm01** [comment]
Agreed. I will try to implement it over the weekend.

**Comment by Hiteshm01** [comment]
Attempted fix @ https://github.com/brianc/node-sql/pull/203

**Pull request merged**
