### PR TITLE
drop index fix for pg

### PR DESCRIPTION
**Pull request by soliton4**
drop index resulted in a sql syntax error on pg.

i also added the option to address indexes in different schemas.

see pg docu DROP INDEX:
http://www.postgresql.org/docs/9.2/static/sql-dropindex.html

### CODE REVIEW

**Comment by brianc** [comment]
I'm not sure why there is so much change in the diff - is git just being weird or did something change I can't seem to see?  If the tests pass I'm good to merge it, but it'd be nice if the diff was a bit more readable :grimacing:

**Comment by soliton4** [comment]
@brianc hi
happy new year

i agree

the change i did was only adding this:

// literaly a copy from the old Postgres version
+// i dont know if it makes sense
+// pls test on a actual mysql db
+Mysql.prototype.visitDropIndex = function(node) {
+  var result = [ 'DROP INDEX' ];
+
+  result.push(this.quote(node.options.indexName));
+  result.push("ON");
+  result.push(this.visit(node.table.toNode()));
+
+  return result;
+};

at the end of the file
the sqlite change is equivalent

the ugly was not regarding the ugly dif however

i am not satisfied with having a duplicated function. also there is no way for me to verify if the drop index is correct for mysql and sqlite. (and if ppls see its wrong they are gonna blame me ;( jk)

hope this helps with the review
thank you

**Comment by soliton4** [comment]
@brianc hi
anything you need me to do here?

**Comment by danrzeppa** [comment]
I would be inclined to dump the second commit since no one is sure of the correct syntax. I would think we'd only want to add features to a platform, that we're reasonably sure work.

If you are inclined to test on the other platforms, I like to use http://sqlfiddle.com/ to test on different platforms since I don't have a local instance of the different DB types node-sql supports.

**Comment by soliton4** [comment]
@danrzeppa there has not been any feature added.
i simply corrected the syntax for postgres.
you did not state how you want to procede with the existing code

**Comment by danrzeppa** [comment]
@soliton4 Maybe I'm missing something, but in commit 221aed0d9c9f9457bfc92461f6c8bf2c105bdd75 it looks like you added the following code:

```javascript
// literaly a copy from the old Postgres version
// i dont know if it makes sense
// pls test on a actual mysql db
Mysql.prototype.visitDropIndex = function(node) {
  var result = [ 'DROP INDEX' ];

  result.push(this.quote(node.options.indexName));
  result.push("ON");
  result.push(this.visit(node.table.toNode()));

  return result;
};
```
to the lib/dialect/mysql.js and lib/dialect/sqlite.js files, with the comment of "I dont know if it makes sense, pls test on actual mysql".

These also happen to be the files that appear to have been heavily changed as @brianc pointed out above. I'm suggesting removing this last commit and just merging in the drop index fix for PostgreSQL, and leave the other dialects alone.

**Comment by soliton4** [comment]
@danrzeppa yes you are missing something
the very first line to be exact
//literaly a copy from the old Postgres version

i copy pasted the code. mysql and sqlite inherited the function from postgres. but since postgres changed i had to copy to code to the mysql and sqlite files in order to preserver their behaviour

**Comment by danrzeppa** [comment]
Alright. I see where I was confused. I was trying to figure out why the diffs where so different as @brianc mentioned, but I haven't been able to see why they would look like that yet.

**Comment by soliton4** [comment]
if the difs are a problem i can try to make another pr.

its been a while since i created the pr but i am pretty sure i only changed the visitDropIndex and its tests

**Comment by danrzeppa** [comment]
I'd try creating another pull request, just to see what happens.

**Comment by soliton4** [comment]
new pr:
https://github.com/brianc/node-sql/pull/210

**Comment by soliton4** [comment]
ok now the new pr should be ok
https://github.com/brianc/node-sql/pull/210

please give feedback or merge.  
thank you very much

**Pull request closed without merging**
