### PR TITLE
Updated some tests to include coverage for Microsoft SQL Server (and other change).

### PR DESCRIPTION
**Pull request by danrzeppa**
Noticed that there wasn't complete coverage for Microsoft SQL Server in the tests. I'm sure I'll be finding a number of these since I added the Microsoft stuff quite a while ago and things have changed.

### CODE REVIEW

**Comment by danrzeppa** [comment]
@brianc Looks like I kind of screwed this pull request up. Still getting used to things. There is another feature in this pull request in addition to the updated where clause tests. Basically it allows you to use AND and OR without first having to use WHERE. For example, I find myself writing things like:

```javascript
var query=user.select()
if (xxx){
  query.where()
}
if (yyy){
  query.and()
}
```
But If the xxx `if` doesn't execute, then things blow up. This pull request allows you to do:

```javascript
var query=user.select()
query.and(user.name.equals('joe')
```
and end up with
```sql
SELECT * FROM user where user.name = 'joe'
```
What do you think?

**Comment by brianc** [comment]
I completely dig this feature. It's a great idea! Your tests are comprehensive too. :100:

**Comment by brianc** [comment]
No worries on not having total coverage on the mssql stuff yet either. Happy to merge in more as you find 'em.  In the meanwhile, you cool with me pushing a new minor version which contains your new fix here?

**Comment by danrzeppa** [comment]
I'm good with merging in the changes.

**Comment by brianc** [comment]
:dancer: awesome! :tada:

**Comment by brianc** [comment]
pushing a new minor version to npm now

**Pull request merged**
