### PR TITLE
don't use alias in binary clause

### PR DESCRIPTION
**Pull request by bergos**
An alias/"AS" in a binary clause causes an error. This patch set's the property value to the name value to prevent an alias in the SQL query.

### CODE REVIEW

**Comment by brianc** [comment]
:+1: looks good to me! Want a new minor version? :smile:

**Comment by bergos** [comment]
Looks like github automatically added my latest commit to this pull request somehow?

The right topic would be: Support for Postgres DISTINCT ON
Tests are included.

**Comment by bergos** [comment]
Looks like the pull request isn't included in the latest version. Can you please merge it, so it will be part of the next version?

**Comment by brianc** [comment]
Sounds good! Sorry for missing this one. Will push it out now.

**Pull request merged**
