### PR TITLE
Adding specific constraint to table definition

### PR DESCRIPTION
**Pull request by BeeDi**
My use case is the need to add a specific constraint, e.g. DEFERRABLE INITIALLY DEFERRED to definition of my tables. 
I added a simple "constraint" property, please tell me if there is anything I can do.

### CODE REVIEW

**Comment by brianc** [comment]
Hi! sorry for taking a while to get back to you on this, but first of all I really appreciate this! Is there a way you could write a test for this feature before I merge it? I like all the features to have test backing them - it keeps maintence easier long term. :)

**Comment by BeeDi** [comment]
I added some tests ;) could you check and tell me if it seems enough ?

**Comment by brianc** [comment]
@BeeDi your tests look fabulous!  Mind bringing this into a place where I can merge it in? Sorry for taking a while, now there's a merge conflict. :tired_face: 

Once it merges cleanly I'll add it & push a new version to npm!

**Comment by BeeDi** [comment]
Done :)

**Comment by brianc** [comment]
Sorry again for the delay! Been traveling a lot - scheduled some OSS time weekly now so I should be better about being on top of things.  I appreciate the effort here - merging & pushing a new minor version today.

**Pull request merged**
