### PR TITLE
Just use Array#map.

### PR DESCRIPTION
**Pull request by braddunbar**
No need to _.map here when Array#map will do. :)

### CODE REVIEW

**Comment by braddunbar** [comment]
*Note: Build fixed in #308.*

**Comment by spion** [comment]
Afaik array.map is significantly slower

**Comment by braddunbar** [comment]
Perhaps, but I don't think it's worth the indirection in this case. Further, `Array#map` is used ~40 times as opposed to `_.map`.

**Comment by PlasmaPower** [comment]
Yes, it's because Array.map looks at the keys, whereas _.map loops from 0 to the length. For example, in this scenario Array.map will log twice, and _.map will log 3 times.

```
var arr = ['a'];
arr[2] = 'b';

arr.map(console.log.bind(console));
_.map(arr, console.log.bind(console));
```

Performance tests here: https://jsperf.com/array-map-vs-lo-dash-map

**Comment by braddunbar** [comment]
@brianc Ping!

**Comment by braddunbar** [comment]
Ping! 🙃

**Pull request closed without merging**
