### PR TITLE
fixes drop index statement for pg

### PR DESCRIPTION
**Pull request by soliton4**
there that should be much more readable

since the last pr caused some confusion when i kept the old syntax for mysql and sqlite, i made the change simpler by changing it for all dialects.

### CODE REVIEW

**Comment by soliton4** [comment]
it took me a while to find the time to fix this. 
it was not obvious at first sight that mysql uses different quotes.

i hope its ok to have this in 2 commits.

**Comment by danrzeppa** [comment]
According to http://dev.mysql.com/doc/refman/5.7/en/drop-index.html it looks like the syntax for MySQL is the way it is currently with the ON statement.

**Comment by brianc** [comment]
Yah totally fine to have it in two commits - sorry for taking a while to get around to this - been working at a new job & pretty busy.  Whenever you're happy w/ the changes here feel free to merge & ping me & I can release a new version to npm. :)

**Comment by brianc** [comment]
This is good to merge, right? It looks good to me...but I wanna check w/ the original author: @soliton4 ?

**Comment by soliton4** [comment]
@brianc i gave a talk about https://github.com/soliton4/promiseland-pg yesterday and mentioned that i had to use my own version of node-sql because of unpatched fixes.
sorry i didnt have the time yet to follow up on the merge process.

will try to do so. if you think its ok to merge go ahead thou.

btw can you tell me your oppinion on https://github.com/soliton4/promiseland-pg ?

**Comment by brianc** [comment]
That is really radical!  I dig it.  Are you using ES6 or something for promiseland? Cool syntax.  That looks like a nice little orm-style thing with cool "sync" looking access to postgres via generators too!

I'll go ahead & merge this in so you don't have to use your fork anymore, and I'll push a new version to npm!

**Comment by brianc** [comment]
Published @0.50.0

**Comment by soliton4** [comment]
@brianc promiseland is a way to create readable async code in ES5 compatible runtime environments

in addition it has a typesafety feature which has a modifier "savable"

it allows you to create a generic storage engine that is completely seperate from the program logic.

if you want to learn more i will give a talk about it at the next amsterdam.js meetup. where are you located?

**Comment by soliton4** [comment]
@brianc p.s.: http://promise-land.net/

**Pull request merged**
